# Generated by Django 2.1.1 on 2018-10-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developers',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='developers',
            old_name='programming_language',
            new_name='programming_languages',
        ),
    ]
