# Generated by Django 2.1.1 on 2018-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviews',
            old_name='developer',
            new_name='developers',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='developer',
            new_name='developers',
        ),
        migrations.RenameField(
            model_name='programminglanguages',
            old_name='developer',
            new_name='developers',
        ),
    ]
