# Generated by Django 2.1.1 on 2018-09-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersearch', '0002_auto_20180930_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviews',
            old_name='developers',
            new_name='developer',
        ),
    ]
